anuragverma108/DSA-Placement-Probems

- C++/Array/Kadane.cpp
Hii @anuragverma108  I have added the code please review and do let me know if any changes required 
Thanks.
> Added Kadane Algorithm for #8

- C++/Array/10- Transpose of a matrix in c.c
- C++/Array/11 - Matrix Multiplication in c.c
Solved in c to find the transpose of a matrix
> Create 10- Transpose of a matrix in c.c

- C++/Array/11-Matrix Multiplication in C.c
Solved Matrix Multiplication in c
> Create 11-Matrix Multiplication in C.c

- C++/Array/Bubble_sort.cpp
> Bubble_sort.cpp

- C++/Array/19-Quick_Sort_Algorithm.cpp
Here I have provided a detailed explanation of `Quick sort sorting algorithm` with **_proper explanations and comments_**, which in a way will **_provide clear and concise understanding_** of the concept.
> Added CPP Quick Sort Algorithm

- C++/Array/19_MergeSortedArrays.cpp
Problem to Merge two sorted arrays without Extra Space in C++
Can you please review and merge the PR for the issue #31.
> Added 19_MergeSortedArrays.cpp

- C++/Array/20-BST_Same_Tree.cpp
I have added a **CPP algorithm** of BST to check whether `given two trees are same or not`.
> Added BST Same Tree Algorithm

- .gitignore
- .vscode/settings.json
- C++/Dynamic Programming/Number_of_ways_of_cutting_a_pizza.cpp
Added gitignore file and provided solution for leetcode problem no: 1444 with DP approach and also created new folder named DP for further use in similar kind of problem
> Added Gitignore file and Added Solution of leetcode 1444

- C++/Stack/reverse_a_stack.cpp
created a new folder for Stack DS problems and added Reverse a Stack problem with the brute force and recursive solution
> add reverse a stack problem (GFG)

- C++/Stack/Max_data_node.cpp
Here, it is the Max data node code file.
Issue #49
> adding Max_data_node code

- C++/Stack/Stack_using_LL.cpp
This file contains Stack using LL Code.
Issue #50
> adding Stack using LL

- C++/Stack/Reverse_a_stack_using_recursion.cpp
This file contains a code of reverse a stack using recursion.
Isuue #52
> Adding reverse a stack using recursion

- C++/Linked List/Swap_Nodes_ in_Pairs.cpp
> Create 1.Swap_Nodes_ in_Pairs.cpp

- C++/Array/RAINWATER_TRAPPING.cpp
> rainwater problem

- binary_tree_to_doubly_linked_list.cpp
> Code added

- C++/Dynamic Programming/nCr.cpp
Calculation of nCr using dynamic programming.
example n = 5, r = 2 -> nCr = 10
@anuragverma108 I have done the needful, please review it.
Thankyou
> Pushing algorithm to calculate nCr

- C++/Array/binary_search.cpp
hey @anuragverma108 ! I have pushed the required files for binary search. Kindly review the following.
>  Binary search file

- C++/Queue/CircularQueue.cpp
- C++/Queue/DoubleEndedQueue.cpp
- C++/Queue/PriorityQueue.cpp
- C++/Queue/Questions/PalindromeInQueue.cpp
- C++/Queue/Questions/ReverseQueue.cpp
- C++/Queue/Queue.cpp
Hey @anuragverma108 
Issue Ref: https://github.com/anuragverma108/DSA-Placement-Probems/issues/81
I have successfully added different types of queue code, namely priority queue, circular queue, double-ended queue, simple queue, and two sample questions. Please review the PR.
Thank you.
> Added Queue Codes With Sample Queue Questions

- C++/Array/majority_element.cpp
> N/2 occurence, optimal solution
> added majority_element.cpp

- C++/Dynamic Programming/Power_Of_Numbers.cpp
Fixes #96 
@anuragverma108 I have pushed the necessary algorithm. Please review it.
Thank you
> Power of numbers

- C++/Dynamic Programming/Power_Of_Numbers.cpp
- C++/Linked List/Y_shape_ll.cpp
Hey @anuragverma108, I have pushed the necessary code file for the problem statement. Fixes #107 
Could u please merge it after adding the necessary HACKTOBER fest labels.
Thank you
> Finding Intersection Point in Y-shaped Linked List
